M48
; DRILL file {KiCad (6.0.2)} date Sun Jan 29 12:52:27 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-29T12:52:27-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X111.275Y-100.995
X116.125Y-100.995
T2
X110.975Y-104.025
X116.425Y-104.025
T3
X53.0Y-53.0
X53.0Y-103.0
X129.0Y-53.0
X129.0Y-103.0
T0
M30
